@echo off
echo Configuring C6809 sources for the Windows (MinGW) platform...

echo # generated by fixmingw.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile

echo Done!
